###
GET http://localhost:3000/posts

###
GET http://localhost:3000/post/1

###
GET http://localhost:3000/posts/user/1

###
POST http://localhost:3000/post/create
Content-Type: application/json

{
    "userId": 1,
    "id": 3,
    "title": "Lorem ipsum",
    "body": "Lorem ipsum dolor sit amet, this is just dummy text"
}

###
DELETE http://localhost:3000/post/delete/2