###
GET http://localhost:3000/posts

###
GET http://localhost:3000/post/1

###
GET http://localhost:3000/posts/user/1

###
POST http://localhost:3000/post/create
Content-Type: application/json

{
    "userId": 3,
    "id": 13,
    "title": "Lorem ipsum",
    "body": "Lorem ipsum dolor sit amet, this is just dummy text"
}

###
DELETE http://localhost:3000/post/delete/12

###
PUT http://localhost:3000/post/update/6006f394fee6f02f8804bbeb
Content-Type: application/json

{
    "_id": "6006f394fee6f02f8804bbeb",
    "userId": 3,
    "id": 14,
    "title": "Lorem ipsum",
    "body": "This is my new post with just dummy text, updated via my own REST API",
    "createdAt": "2021-01-18T15:25:35.333Z",
    "updatedAt": "2021-01-18T15:57:41.889Z"
}